//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> ArticleId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
